language: objective-c  #1
osx_image: xcode8.2 #2
xcode_project: Supermarket Register/Supermarket Register.xcodeproj #3
xcode_scheme: Supermarket Register #4
xcode_sdk: iphonesimulator8.3 #5

script:
    - xcodebuild clean build test -sdk iphonesimulator -project buybar-ios/buybar.xcodeproj -scheme buybar CODE_SIGNING_REQUIRED=NO -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3'
