language: objective-c  #1
osx_image: xcode8.2 #2
xcode_project: Supermarket Register/Supermarket Register.xcodeproj #3
xcode_scheme: Supermarket Register #4
xcode_sdk: iphonesimulator8.3 #5
before_script:
    - gem install xcodeproj
script:
    - cd buybar-ios && xcodebuild -list && ./recreate_user_schemes.rb && xcodebuild clean build test -sdk iphonesimulator -project buybar.xcodeproj CODE_SIGNING_REQUIRED=NO -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3'
