# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'buybar' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'

  # Pods for buybar

  target 'buybarTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'buybarUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
