# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "10.0"
use_frameworks!

target 'buybar' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', "~> 4.4"

  # Pods for buybar

  target 'buybarTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'buybarUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
